name: Push dist

on:
  push:
    branches:
      - main
      - master

jobs:
  push-dist:
    name: Push dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build # Add whatever you need to build your package here
      - name: Push dist to gh-pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git subtree push --prefix dist origin gh-pages2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}